// zengtrade: Supabase Auth "Send Email" hook (Supabase Edge Function, Deno).
// Supabase's own built-in mailer has been silently failing to dispatch auth emails for this
// project (confirmed 2026-09-18: every /auth/v1/signup call returns 500 "Error sending
// confirmation email", even with verified-working SMTP credentials, a fully completed native
// Resend<->Supabase integration, and no Auth Hook previously configured - the failure is inside
// Supabase's own service, not anything in our config). This hook intercepts EVERY auth email
// (signup confirmation, password recovery, magic link, email change, invite) before Supabase's
// built-in mailer ever runs, and sends it ourselves via Resend's HTTP API directly - the same
// path already proven reliable by hand-testing it repeatedly against this exact domain/key.
//
// Secrets (set with `supabase secrets set ...`, NEVER in code/frontend):
//   RESEND_API_KEY          : Resend -> API keys (full access)
//   SEND_EMAIL_HOOK_SECRET  : generated by Supabase when the "Send Email" hook is created in
//                             Authentication -> Auth Hooks, format "v1,whsec_..."
import { Webhook } from "npm:standardwebhooks@^1";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") ?? "";
const HOOK_SECRET = (Deno.env.get("SEND_EMAIL_HOOK_SECRET") ?? "").replace("v1,whsec_", "");
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SITE = "https://zengtrade.in";
const FROM = "zengtrade <noreply@zengtrade.in>";

type EmailData = {
  token: string;
  token_hash: string;
  redirect_to: string;
  email_action_type: string;
  site_url: string;
  token_new?: string;
  token_hash_new?: string;
};

// Same badge mark used across the product (assets/app.js brand-logo, the confirm-signup template),
// reproduced inline so this email never depends on an external image loading.
const LOGO_SVG = `<svg width="28" height="28" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" style="vertical-align:middle;display:inline-block">
  <rect width="32" height="32" rx="8" fill="#00AB4E"/>
  <path d="M24.69 13.67A9 9 0 1 1 20.5 8.21" stroke="#fff" stroke-width="2.5" fill="none" stroke-linecap="round"/>
  <path d="M12.5 19.5L17 15L20 17.5L26.5 8.8" stroke="#fff" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
</svg>`;

function shell(heading: string, body: string, cta: { label: string; url: string }): string {
  return `<div style="font-family:'Helvetica Neue',Arial,sans-serif;max-width:480px;margin:0 auto;padding:28px 24px;color:#0f1a2a">
  <div style="margin-bottom:24px">
    ${LOGO_SVG}
    <span style="font-weight:800;font-size:19px;color:#0f1a2a;vertical-align:middle;margin-left:9px">zengtrade</span>
  </div>
  <h1 style="font-size:22px;line-height:1.25;margin:0 0 10px">${heading}</h1>
  <p style="color:#5c6a7e;font-size:15px;line-height:1.65;margin:0 0 24px">${body}</p>
  <a href="${cta.url}" style="display:inline-block;background:#00AB4E;color:#04140a;font-weight:700;font-size:15px;text-decoration:none;padding:13px 28px;border-radius:10px">${cta.label}</a>
  <p style="color:#94a3b8;font-size:12px;line-height:1.6;margin:26px 0 0;border-top:1px solid #e6eaf1;padding-top:16px">
    If you didn't request this, you can safely ignore this email. zengtrade is educational software and paper-first, not investment advice.
  </p>
</div>`;
}

// GoTrue no longer builds the verification link for us once a Send Email hook is active - we
// build it the same way GoTrue itself would, per Supabase's documented custom-email-hook pattern.
function verifyUrl(d: EmailData, tokenHash: string, type: string): string {
  const u = new URL(`${SUPABASE_URL}/auth/v1/verify`);
  u.searchParams.set("token", tokenHash);
  u.searchParams.set("type", type);
  u.searchParams.set("redirect_to", d.redirect_to || SITE);
  return u.toString();
}

function renderEmail(user: { email: string }, d: EmailData): { subject: string; html: string } {
  switch (d.email_action_type) {
    case "signup":
    case "email":
      return {
        subject: "Confirm your zengtrade email",
        html: shell(
          "Confirm your email",
          "Welcome to zengtrade. Confirm your email to start paper-trading regime-aware strategies on live data, free, with no card.",
          { label: "Confirm email", url: verifyUrl(d, d.token_hash, d.email_action_type) }
        ),
      };
    case "recovery":
      return {
        subject: "Reset your zengtrade password",
        html: shell(
          "Reset your password",
          "We received a request to reset the password for your zengtrade account. If this wasn't you, you can ignore this email, your password won't change.",
          { label: "Reset password", url: verifyUrl(d, d.token_hash, "recovery") }
        ),
      };
    case "magiclink":
      return {
        subject: "Your zengtrade sign-in link",
        html: shell(
          "Sign in to zengtrade",
          "Click below to sign in. This link works once and expires shortly for your security.",
          { label: "Sign in", url: verifyUrl(d, d.token_hash, "magiclink") }
        ),
      };
    case "email_change":
      return {
        subject: "Confirm your new zengtrade email",
        html: shell(
          "Confirm your new email",
          `Confirm this address to finish updating the email on your zengtrade account to ${user.email}.`,
          { label: "Confirm new email", url: verifyUrl(d, d.token_hash_new || d.token_hash, "email_change") }
        ),
      };
    case "invite":
      return {
        subject: "You've been invited to zengtrade",
        html: shell(
          "You're invited",
          "You've been invited to join zengtrade, paper-trade regime-aware crypto strategies on live data, free, with no card.",
          { label: "Accept invite", url: verifyUrl(d, d.token_hash, "invite") }
        ),
      };
    default:
      return {
        subject: "zengtrade account update",
        html: shell(
          "Account update",
          "There's an update on your zengtrade account.",
          { label: "Open zengtrade", url: SITE }
        ),
      };
  }
}

Deno.serve(async (req) => {
  if (req.method !== "POST") return Response.json({ error: "method not allowed" }, { status: 405 });
  const payload = await req.text();
  const headers = Object.fromEntries(req.headers);
  try {
    const wh = new Webhook(HOOK_SECRET);
    const verified = wh.verify(payload, headers) as { user: { email: string }; email_data: EmailData };
    const { subject, html } = renderEmail(verified.user, verified.email_data);

    const resp = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({ from: FROM, to: [verified.user.email], subject, html }),
    });
    if (!resp.ok) {
      const detail = await resp.text().catch(() => "");
      throw new Error(`Resend send failed: ${resp.status} ${detail}`);
    }
    return Response.json({});
  } catch (e) {
    console.error("auth-send-email failed:", e);
    return Response.json({ error: { http_code: 500, message: String(e) } }, { status: 500 });
  }
});
